/* Generated by scripts/build-glyphs.ts from src/icons/lemonnade/*.svg — do not edit. Run `npm run glyphs`. */
// Lemonnade icons: drawn for L3, not part of Material Symbols (👁️ Lemonnade V3 → Icons in Figma, exported 24×24).
// Add an icon by dropping its SVG here and running `npm run glyphs`. Use with <Icon icon={lmSwitchArrowVertical} />.
export { lmSwitchArrowHorizontal, lmSwitchArrowVertical } from '../../components/icons/glyphs'
