// Turns the SVGs the components use into `data:` URI string modules, so components never import .svg files.
// An .svg import means something different in every bundler (a URL in Vite, an object in Next.js, a React component
// with SVGR) — a string in a .ts file works everywhere, needs no bundler setup and no CORS headers for CSS masks.
// The .svg files stay the source of truth; this regenerates the modules from them.
//
//   npm run glyphs                         regenerate the component modules (also runs before dev / build)
//   npm run -s glyphs -- --pick add,search > icons.ts    a module with just those Material icons, for an app
//
// Run with Node (it strips the TS types natively).

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const repo = fileURLToPath(new URL('../', import.meta.url))
const MATERIAL = 'src/icons/material/rounded/'
const LEMONNADE = 'src/icons/lemonnade/'
const COMPONENTS = 'src/components/'
const header = (what: string, run = 'npm run glyphs') => `/* Generated by scripts/build-glyphs.ts from ${what} — do not edit. Run \`${run}\`. */\n`

/** SVG markup → data URI: quotes made single (the URI sits in url("…")), only the characters that need it encoded. */
export function toDataUri(svg: string) {
  const clean = svg
    .replace(/<\?xml[^>]*\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .trim()
    .replace(/\s+/g, ' ')
    .replace(/"/g, "'")
    .replace(/[\r\n%#()<>?[\\\]^`{|}]/g, encodeURIComponent)
  return `data:image/svg+xml,${clean}`
}

const read = (path: string) => readFileSync(repo + path, 'utf8')
const camel = (file: string) => file.replace(/\.svg$/, '').replace(/[-_](\w)/g, (_, c: string) => c.toUpperCase())
const pascal = (file: string) => camel(file).replace(/^\w/, (c) => c.toUpperCase())
const line = (name: string, path: string, doc: string) => `/** ${doc} */\nexport const ${name} = ${JSON.stringify(toDataUri(read(path)))}\n`

/** msAdd → rounded/add.svg, msContentCopyFill → rounded/content_copy-fill.svg (from the Material index). */
function materialFiles() {
  const map = new Map<string, string>()
  for (const m of read('src/icons/material/index.ts').matchAll(/export \{ default as (\w+) \} from '\.\/rounded\/([^']+)'/g)) map.set(m[1], m[2])
  return map
}

if (process.argv.includes('--pick')) {
  // An app's own icon module: only the icons it uses, as strings for <Icon icon={…}>.
  const names = (process.argv[process.argv.indexOf('--pick') + 1] ?? '').split(',').map((s) => s.trim()).filter(Boolean)
  const files = new Map([...materialFiles()].map(([name, file]) => [file.replace(/\.svg$/, ''), name]))
  const out = names.map((n) => {
    const name = files.get(n)
    if (!name) throw new Error(`No Material Symbols icon "${n}" (use the file name, e.g. arrow_back or arrow_back-fill)`)
    return line(name, MATERIAL + n + '.svg', `Material Symbols Rounded: ${n}`)
  })
  process.stdout.write(header('Material Symbols Rounded', `npm run -s glyphs -- --pick ${names.join(',')}`) + '\n' + out.join('\n'))
  process.exit(0)
}

// 1. src/components/icons/glyphs.ts — the Material icons the components import from it, every Lemonnade icon, and the
//    component graphics in src/components/icons/assets.
const files = (dir: string) => readdirSync(repo + dir).filter((f) => f.endsWith('.svg')).sort()
const sources = readdirSync(repo + COMPONENTS, { recursive: true, encoding: 'utf8' }).filter((f) => /\.tsx?$/.test(f))
const used = new Set<string>()
for (const f of sources) {
  for (const m of read(COMPONENTS + f).matchAll(/import \{([^}]+)\} from '[./]*(?:icons\/)?glyphs'/g)) {
    for (const name of m[1].split(',').map((s) => s.trim())) if (/^ms[A-Z]/.test(name)) used.add(name)
  }
}
const material = materialFiles()
const glyphs = [
  ...[...used].sort().map((name) => {
    const file = material.get(name)
    if (!file) throw new Error(`${name} is imported from glyphs but isn't a Material Symbols icon`)
    return line(name, MATERIAL + file, `Material Symbols Rounded: ${file.replace(/\.svg$/, '')}`)
  }),
  ...files(LEMONNADE).map((f) => line('lm' + pascal(f), LEMONNADE + f, `Lemonnade icon: ${f.replace(/\.svg$/, '')} (👁️ Lemonnade V3 → Icons)`)),
  ...files(COMPONENTS + 'icons/assets/').map((f) => line(camel(f), COMPONENTS + 'icons/assets/' + f, `Component graphic: ${f}`)),
]
writeFileSync(repo + COMPONENTS + 'icons/glyphs.ts', header('src/icons and src/components/icons/assets') + '\n' + glyphs.join('\n'))

// The public Lemonnade icon set (src/icons/lemonnade) re-exports the same strings, so there's one copy of each.
const lm = files(LEMONNADE).map((f) => 'lm' + pascal(f))
writeFileSync(
  repo + LEMONNADE + 'index.ts',
  header(LEMONNADE + '*.svg') +
    `// Lemonnade icons: drawn for L3, not part of Material Symbols (👁️ Lemonnade V3 → Icons in Figma, exported 24×24).\n` +
    `// Add an icon by dropping its SVG here and running \`npm run glyphs\`. Use with <Icon icon={lmSwitchArrowVertical} />.\n` +
    `export { ${lm.join(', ')} } from '../../components/icons/glyphs'\n`,
)

// 2. <Component>/glyphs.ts for components with their own artwork in <Component>/assets (used from TS, not CSS).
const own = ['Button', 'BottomNavbar']
for (const c of own) {
  const dir = COMPONENTS + c + '/assets/'
  if (!existsSync(repo + dir)) throw new Error(`${dir} is missing`)
  const out = files(dir).map((f) => line(camel(f), dir + f, `${c} graphic: ${f}`))
  writeFileSync(repo + COMPONENTS + c + '/glyphs.ts', header(dir) + '\n' + out.join('\n'))
}

console.log(`glyphs: ${used.size} Material, ${files(LEMONNADE).length} Lemonnade, ${files(COMPONENTS + 'icons/assets/').length} component graphics; ${own.join(', ')} artwork`)
