// Builds CSS custom properties + TS types from the DTCG sources in src/tokens/source.
// Run with `npm run tokens` (Node strips the TS types natively).

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { themes, defaultProduct, defaultMode, productModes } from '../src/tokens/themes.ts'

const root = fileURLToPath(new URL('../src/tokens/', import.meta.url))
const OPACITY_EXT = 'l3.opacity'

type Leaf = { $type: string; $value: string | number; $extensions?: Record<string, string> }
type Tree = { [key: string]: Tree | Leaf }

const readJson = (path: string): Tree => JSON.parse(readFileSync(root + path, 'utf8'))
const isLeaf = (node: Tree | Leaf): node is Leaf => '$value' in node

function flatten(tree: Tree, prefix: string[] = [], out = new Map<string, Leaf>()) {
  for (const [key, node] of Object.entries(tree)) {
    if (isLeaf(node)) out.set([...prefix, key].join('.'), node)
    else flatten(node, [...prefix, key], out)
  }
  return out
}

const refPath = (value: string) => {
  const match = /^\{(.+)\}$/.exec(value)
  if (!match) throw new Error(`Expected a {reference}, got ${value}`)
  return match[1]
}

// `component.button.buy.surface` → `--l3-button-buy-surface`; base/opacity keep their group prefix.
const varName = (path: string) =>
  '--l3-' + path.replace(/^component\./, '').replaceAll('.', '-')

const base = flatten(readJson('source/base.colors.json'))
const opacity = flatten(readJson('source/base.opacity.json'))

// ---- base.css -------------------------------------------------------------
const baseLines = [
  ...[...base].map(([path, leaf]) => `  ${varName(path)}: ${leaf.$value};`),
  ...[...opacity].map(([path, leaf]) => `  ${varName(path)}: ${leaf.$value};`),
]

// ---- themes.css -----------------------------------------------------------
const themeTokens = themes.map((theme) => ({ theme, tokens: flatten(readJson(`source/themes/${theme.id}.json`)) }))
const tokenPaths = [...themeTokens[0].tokens.keys()]

function cssValue(leaf: Leaf, tokens: Map<string, Leaf>, themeId: string, path: string): string {
  const target = refPath(String(leaf.$value))
  if (!base.has(target) && !tokens.has(target)) throw new Error(`${themeId}: ${path} → unknown ${target}`)
  const color = `var(${varName(target)})`
  const opacityRef = leaf.$extensions?.[OPACITY_EXT]
  if (!opacityRef) return color
  const step = opacity.get(refPath(opacityRef))
  if (!step) throw new Error(`${themeId}: ${path} → unknown ${opacityRef}`)
  return `color-mix(in srgb, ${color} ${Math.round(Number(step.$value) * 100)}%, transparent)`
}

function selectorFor(theme: (typeof themes)[number]) {
  // Single-mode products match on product alone, so any requested mode resolves.
  const sel = productModes[theme.product].length === 1
    ? `[data-product="${theme.product}"]`
    : `[data-product="${theme.product}"][data-mode="${theme.mode}"]`
  return theme.product === defaultProduct && theme.mode === defaultMode ? `:root,\n${sel}` : sel
}

const themeBlocks = themeTokens.map(({ theme, tokens }) => {
  const missing = tokenPaths.filter((p) => !tokens.has(p))
  const extra = [...tokens.keys()].filter((p) => !tokenPaths.includes(p))
  if (missing.length || extra.length) throw new Error(`${theme.id}: token set differs (${[...missing, ...extra].join(', ')})`)
  const lines = tokenPaths.map((p) => `  ${varName(p)}: ${cssValue(tokens.get(p)!, tokens, theme.id, p)};`)
  return `/* ${theme.figmaMode} */\n${selectorFor(theme)} {\n  color-scheme: ${theme.mode};\n${lines.join('\n')}\n}`
})

// ---- tokens.ts ------------------------------------------------------------
const figmaName = (path: string) => path.replaceAll('.', '/')

const header = '/* Generated by scripts/build-tokens.ts from src/tokens/source — do not edit. */\n'
mkdirSync(root + 'generated', { recursive: true })
writeFileSync(root + 'generated/base.css', `${header}:root {\n${baseLines.join('\n')}\n}\n`)
writeFileSync(root + 'generated/themes.css', `${header}${themeBlocks.join('\n\n')}\n`)
writeFileSync(
  root + 'generated/tokens.ts',
  `${header}
/** Theme token (Figma name without the "🔷 L3/color/" prefix) → CSS custom property. */
export const themeTokenVars = {
${tokenPaths.map((p) => `  '${figmaName(p)}': '${varName(p)}',`).join('\n')}
} as const

/** Base color (Figma name without the "L3-color-base/" prefix) → CSS custom property. */
export const baseColorVars = {
${[...base.keys()].map((p) => `  '${figmaName(p.replace(/^base\./, ''))}': '${varName(p)}',`).join('\n')}
} as const

export type ThemeToken = keyof typeof themeTokenVars
export type BaseColor = keyof typeof baseColorVars
`,
)

console.log(`tokens: ${base.size} base colors, ${opacity.size} opacity steps, ${tokenPaths.length} theme tokens × ${themes.length} themes`)
