// Downloads the complete Material Symbols icon set in the exact style the design uses —
// Rounded · weight 400 · fill off (plus the filled variant) · grade 0 · optical size 24dp —
// straight from Google Fonts, and generates typed, tree-shakable imports.
//
//   npm run icons            # re-sync (only fetches icons that are new or changed)
//
// Output (committed, so the app works offline and icons never change unexpectedly):
//   src/icons/material/rounded/<name>.svg        outline (FILL 0)
//   src/icons/material/rounded/<name>-fill.svg   filled (FILL 1), only when it differs
//   src/icons/material/icons.json                name, categories, tags, hasFill — for the docs browser
//   src/icons/material/index.ts                  `export { default as msSearch } from './rounded/search.svg'` …

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const out = fileURLToPath(new URL('../src/icons/material/', import.meta.url))
const svgDir = out + 'rounded/'
const FAMILY = 'Material Symbols Rounded'
const METADATA = 'https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true'
// Google's release endpoint: default = FILL 0, fill1 = FILL 1; both wght 400, GRAD 0, opsz 24.
const svgUrl = (name: string, variant: 'default' | 'fill1') =>
  `https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded/${name}/${variant}/24px.svg`

type Meta = { name: string; version: number; popularity: number; categories: string[]; tags: string[]; unsupported_families?: string[] }
type Entry = { name: string; categories: string[]; tags: string[]; hasFill: boolean; popularity: number; version: number }

const toIdent = (name: string) => 'ms' + name.split('_').map((p) => p[0].toUpperCase() + p.slice(1)).join('')

async function fetchText(url: string, attempt = 1): Promise<string> {
  const res = await fetch(url)
  if (res.ok) return res.text()
  if (attempt < 4 && res.status >= 500) return fetchText(url, attempt + 1)
  throw new Error(`${res.status} ${url}`)
}

async function pool<T>(items: T[], size: number, work: (item: T) => Promise<void>) {
  let i = 0
  await Promise.all(Array.from({ length: size }, async () => {
    while (i < items.length) await work(items[i++])
  }))
}

const raw = await fetchText(METADATA)
const meta = JSON.parse(raw.slice(raw.indexOf('{'))) as { icons: Meta[] }
const icons = meta.icons.filter((i) => !i.unsupported_families?.includes(FAMILY)).sort((a, b) => a.name.localeCompare(b.name))

mkdirSync(svgDir, { recursive: true })
const previous: Entry[] = existsSync(out + 'icons.json') ? JSON.parse(readFileSync(out + 'icons.json', 'utf8')) : []
const prevVersion = new Map(previous.map((e) => [e.name, e]))

const entries: Entry[] = []
let fetched = 0
await pool(icons, 32, async (icon) => {
  const known = prevVersion.get(icon.name)
  let hasFill: boolean
  if (known && known.version === icon.version && existsSync(`${svgDir}${icon.name}.svg`)) {
    hasFill = known.hasFill
  } else {
    const [outline, filled] = await Promise.all([fetchText(svgUrl(icon.name, 'default')), fetchText(svgUrl(icon.name, 'fill1'))])
    writeFileSync(`${svgDir}${icon.name}.svg`, outline)
    hasFill = filled !== outline
    if (hasFill) writeFileSync(`${svgDir}${icon.name}-fill.svg`, filled)
    fetched++
    if (fetched % 250 === 0) console.log(`  …${fetched} downloaded`)
  }
  entries.push({ name: icon.name, categories: icon.categories, tags: icon.tags.slice(0, 12), hasFill, popularity: icon.popularity, version: icon.version })
})
entries.sort((a, b) => a.name.localeCompare(b.name))

writeFileSync(out + 'icons.json', JSON.stringify(entries) + '\n')

const lines = entries.flatMap((e) => [
  `export { default as ${toIdent(e.name)} } from './rounded/${e.name}.svg'`,
  ...(e.hasFill ? [`export { default as ${toIdent(e.name)}Fill } from './rounded/${e.name}-fill.svg'`] : []),
])
writeFileSync(
  out + 'index.ts',
  `/* Generated by scripts/sync-icons.ts — Material Symbols Rounded, wght 400, GRAD 0, opsz 24. Do not edit. */\n` +
  `/* Import only what you use, e.g. import { msSearch } from '../icons/material' — unused icons are tree-shaken. */\n` +
  lines.join('\n') + '\n',
)

console.log(`icons: ${entries.length} Rounded (${entries.filter((e) => e.hasFill).length} with a filled variant), ${fetched} downloaded this run`)
